services:
  backend:
    container_name: gemini-bot
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    networks:
      - docker-network

networks:
  docker-network:
    driver: bridge
